services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    command: make dev
    user: "${UID}:${GID}"
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:2.8-alpine
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
