services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    command: make dev
    user: "${UID}:${GID}"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:2.8-alpine
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "8081:80"
      - "8443:443"
    depends_on:
      - app

  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
